apiVersion: v1
kind: Service
metadata:
  labels:
    svc: kuard-rs-test-lb-service
  name: kuard-rs-test-lb-service
spec:
  selector:
    app: kuard-rs-test-pod
  ports:
  - name: http
    nodePort: 31372
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local
