apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs-pod
  template:
    metadata:
      labels:
        app: nginx-rs-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.11
