apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Update image to 1.5.0"
  name: web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      run: web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: web-app
    spec:
      containers:
      - image: ikambarov/web-app:1.5.0
        name: web-app
